// Code generated by go run ./scripts/vetted-filters/main.go; DO NOT EDIT.

/* eslint quote-props: 'off', quotes: 'off', comma-dangle: 'off', semi: 'off' */

export default {
    "categories": {
        "general": {
            "name": "filter_category_general",
            "description": "filter_category_general_desc"
        },
        "other": {
            "name": "filter_category_other",
            "description": "filter_category_other_desc"
        },
        "regional": {
            "name": "filter_category_regional",
            "description": "filter_category_regional_desc"
        },
        "security": {
            "name": "filter_category_security",
            "description": "filter_category_security_desc"
        }
    },
    "filters": {
        "1hosts_lite": {
            "name": "1Hosts (Lite)",
            "categoryId": "general",
            "homepage": "https://badmojr.github.io/1Hosts/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt"
        },
        "1hosts_mini": {
            "name": "1Hosts (mini)",
            "categoryId": "general",
            "homepage": "https://badmojr.github.io/1Hosts/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_38.txt"
        },
        "CHN_adrules": {
            "name": "CHN: AdRules DNS List",
            "categoryId": "regional",
            "homepage": "https://github.com/Cats-Team/AdRules",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_29.txt"
        },
        "CHN_anti_ad": {
            "name": "CHN: anti-AD",
            "categoryId": "regional",
            "homepage": "https://anti-ad.net/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_21.txt"
        },
        "HUN_hufilter": {
            "name": "HUN: Hufilter",
            "categoryId": "regional",
            "homepage": "https://github.com/hufilter/hufilter",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_35.txt"
        },
        "IDN_abpindo": {
            "name": "IDN: ABPindo",
            "categoryId": "regional",
            "homepage": "https://github.com/ABPindo/indonesianadblockrules",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_22.txt"
        },
        "IRN_unwanted_iranian_domains": {
            "name": "IRN: PersianBlocker list",
            "categoryId": "regional",
            "homepage": "https://github.com/MasterKia/PersianBlocker",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_19.txt"
        },
        "ITA_filtri_dns": {
            "name": "ITA: Filtri-DNS",
            "categoryId": "regional",
            "homepage": "https://filtri-dns.ga/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_18.txt"
        },
        "KOR_list_kr": {
            "name": "KOR: List-KR DNS",
            "categoryId": "regional",
            "homepage": "https://github.com/List-KR/List-KR",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_25.txt"
        },
        "KOR_youslist": {
            "name": "KOR: YousList",
            "categoryId": "regional",
            "homepage": "https://github.com/yous/YousList",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_15.txt"
        },
        "LIT_easylist_lithuania": {
            "name": "LIT: EasyList Lithuania",
            "categoryId": "regional",
            "homepage": "https://github.com/EasyList-Lithuania/easylist_lithuania",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_36.txt"
        },
        "MKD_macedonian_pi_hole_blocklist": {
            "name": "MKD: Macedonian Pi-hole Blocklist",
            "categoryId": "regional",
            "homepage": "https://github.com/cchevy/macedonian-pi-hole-blocklist",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_20.txt"
        },
        "NOR_dandelion_sprouts_anti_malware_list": {
            "name": "NOR: Dandelion Sprouts nordiske filtre",
            "categoryId": "regional",
            "homepage": "https://github.com/DandelionSprout/adfilt",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_13.txt"
        },
        "POL_polish_filters_for_pi_hole": {
            "name": "POL: Polish filters for Pi-hole",
            "categoryId": "regional",
            "homepage": "https://www.certyficate.it/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_14.txt"
        },
        "SWE_frellwit_swedish_hosts_file": {
            "name": "SWE: Frellwit's Swedish Hosts File",
            "categoryId": "regional",
            "homepage": "https://github.com/lassekongo83/Frellwits-filter-lists/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_17.txt"
        },
        "TUR_turk_adlist": {
            "name": "TUR: turk-adlist",
            "categoryId": "regional",
            "homepage": "https://github.com/bkrucarci/turk-adlist",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_26.txt"
        },
        "VNM_abpvn": {
            "name": "VNM: ABPVN List",
            "categoryId": "regional",
            "homepage": "http://abpvn.com/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_16.txt"
        },
        "adguard_dns_filter": {
            "name": "AdGuard DNS filter",
            "categoryId": "general",
            "homepage": "https://github.com/AdguardTeam/AdGuardSDNSFilter",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt"
        },
        "adway_default_blocklist": {
            "name": "AdAway Default Blocklist",
            "categoryId": "general",
            "homepage": "https://github.com/AdAway/adaway.github.io/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt"
        },
        "curben_phishing_filter": {
            "name": "Phishing URL Blocklist (PhishTank and OpenPhish)",
            "categoryId": "security",
            "homepage": "https://gitlab.com/malware-filter/phishing-filter",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt"
        },
        "dan_pollocks_list": {
            "name": "Dan Pollock's List",
            "categoryId": "general",
            "homepage": "https://someonewhocares.org/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt"
        },
        "dandelion_sprouts_anti_malware_list": {
            "name": "Dandelion Sprout's Anti-Malware List",
            "categoryId": "security",
            "homepage": "https://github.com/DandelionSprout/adfilt",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt"
        },
        "dandelion_sprouts_game_console_adblock_list": {
            "name": "Dandelion Sprout's Game Console Adblock List",
            "categoryId": "other",
            "homepage": "https://github.com/DandelionSprout/adfilt",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt"
        },
        "hagezi_personal": {
            "name": "HaGeZi Personal Black \u0026 White",
            "categoryId": "general",
            "homepage": "https://github.com/hagezi/dns-blocklists",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt"
        },
        "no_google": {
            "name": "No Google",
            "categoryId": "other",
            "homepage": "https://github.com/nickspaargaren/no-google",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_37.txt"
        },
        "nocoin_filter_list": {
            "name": "NoCoin Filter List",
            "categoryId": "security",
            "homepage": "https://github.com/hoshsadiq/adblock-nocoin-list/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt"
        },
        "notracking_hosts_blocklists": {
            "name": "The NoTracking blocklist",
            "categoryId": "general",
            "homepage": "https://github.com/notracking/hosts-blocklists",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt"
        },
        "oisd_basic": {
            "name": "OISD Blocklist Small",
            "categoryId": "general",
            "homepage": "https://oisd.nl/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_5.txt"
        },
        "oisd_full": {
            "name": "OISD Blocklist Big",
            "categoryId": "general",
            "homepage": "https://oisd.nl/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt"
        },
        "perflyst_dandelion_sprout_smart_tv_blocklist_for_adguard_home": {
            "name": "Perflyst and Dandelion Sprout's Smart-TV Blocklist",
            "categoryId": "other",
            "homepage": "https://github.com/Perflyst/PiHoleBlocklist",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt"
        },
        "peter_lowe_list": {
            "name": "Peter Lowe's Blocklist",
            "categoryId": "general",
            "homepage": "https://pgl.yoyo.org/adservers/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt"
        },
        "scam_blocklist_by_durablenapkin": {
            "name": "Scam Blocklist by DurableNapkin",
            "categoryId": "security",
            "homepage": "https://github.com/durablenapkin/scamblocklist",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt"
        },
        "staklerware_indicators_list": {
            "name": "Stalkerware Indicators List",
            "categoryId": "security",
            "homepage": "https://github.com/AssoEchap/stalkerware-indicators",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt"
        },
        "steven_blacks_list": {
            "name": "Steven Black's List",
            "categoryId": "general",
            "homepage": "https://github.com/StevenBlack/hosts",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt"
        },
        "the_big_list_of_hacked_malware_web_sites": {
            "name": "The Big List of Hacked Malware Web Sites",
            "categoryId": "security",
            "homepage": "https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt"
        },
        "urlhaus_filter_online": {
            "name": "Malicious URL Blocklist (URLHaus)",
            "categoryId": "security",
            "homepage": "https://urlhaus.abuse.ch/",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt"
        },
        "windowsspyblocker_hosts_spy_rules": {
            "name": "WindowsSpyBlocker - Hosts spy rules",
            "categoryId": "other",
            "homepage": "https://github.com/crazy-max/WindowsSpyBlocker",
            "source": "https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt"
        }
    }
}
