import AccessList, { IAccessList } from './AccessList';

// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export type IAccessListResponse = IAccessList;
export default AccessList;
