// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IBlockedServicesArray {
}

export default class BlockedServicesArray {
    constructor(props: IBlockedServicesArray) {
    }

    serialize(): IBlockedServicesArray {
        const data: IBlockedServicesArray = {
        };
        return data;
    }

    validate(): string[] {
        const validate = {
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: Partial<IBlockedServicesArray>): BlockedServicesArray {
        return new BlockedServicesArray({ ...this.serialize(), ...props });
    }
}
