// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IClientsFindResponse {
}

export default class ClientsFindResponse {
    constructor(props: IClientsFindResponse) {
    }

    serialize(): IClientsFindResponse {
        const data: IClientsFindResponse = {
        };
        return data;
    }

    validate(): string[] {
        const validate = {
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: Partial<IClientsFindResponse>): ClientsFindResponse {
        return new ClientsFindResponse({ ...this.serialize(), ...props });
    }
}
