// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IClientsArray {
}

export default class ClientsArray {
    constructor(props: IClientsArray) {
    }

    serialize(): IClientsArray {
        const data: IClientsArray = {
        };
        return data;
    }

    validate(): string[] {
        const validate = {
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: Partial<IClientsArray>): ClientsArray {
        return new ClientsArray({ ...this.serialize(), ...props });
    }
}
