// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IClientsAutoArray {
}

export default class ClientsAutoArray {
    constructor(props: IClientsAutoArray) {
    }

    serialize(): IClientsAutoArray {
        const data: IClientsAutoArray = {
        };
        return data;
    }

    validate(): string[] {
        const validate = {
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: Partial<IClientsAutoArray>): ClientsAutoArray {
        return new ClientsAutoArray({ ...this.serialize(), ...props });
    }
}
