// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IRewriteList {
}

export default class RewriteList {
    constructor(props: IRewriteList) {
    }

    serialize(): IRewriteList {
        const data: IRewriteList = {
        };
        return data;
    }

    validate(): string[] {
        const validate = {
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: Partial<IRewriteList>): RewriteList {
        return new RewriteList({ ...this.serialize(), ...props });
    }
}
