// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IUpstreamsConfigResponse {
}

export default class UpstreamsConfigResponse {
    constructor(props: IUpstreamsConfigResponse) {
    }

    serialize(): IUpstreamsConfigResponse {
        const data: IUpstreamsConfigResponse = {
        };
        return data;
    }

    validate(): string[] {
        const validate = {
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: Partial<IUpstreamsConfigResponse>): UpstreamsConfigResponse {
        return new UpstreamsConfigResponse({ ...this.serialize(), ...props });
    }
}
