/* eslint-disable */
// AUTO-GENERATED by `npm run locales:generate`.  Do not edit by hand.
// Source: .twosky.json → project_id: home_v2 → languages
// Excludes: (none)

export type LocaleMessage = Record<string, string>;

import en from 'panel/__locales/en.json';

export const LOCALE_LOADERS: Record<string, () => Promise<any>> = {
    ar: () => import(/* webpackChunkName: "locale.ar" */ 'panel/__locales/ar.json'),
    be: () => import(/* webpackChunkName: "locale.be" */ 'panel/__locales/be.json'),
    bg: () => import(/* webpackChunkName: "locale.bg" */ 'panel/__locales/bg.json'),
    cs: () => import(/* webpackChunkName: "locale.cs" */ 'panel/__locales/cs.json'),
    da: () => import(/* webpackChunkName: "locale.da" */ 'panel/__locales/da.json'),
    de: () => import(/* webpackChunkName: "locale.de" */ 'panel/__locales/de.json'),
    es: () => import(/* webpackChunkName: "locale.es" */ 'panel/__locales/es.json'),
    fa: () => import(/* webpackChunkName: "locale.fa" */ 'panel/__locales/fa.json'),
    fi: () => import(/* webpackChunkName: "locale.fi" */ 'panel/__locales/fi.json'),
    fr: () => import(/* webpackChunkName: "locale.fr" */ 'panel/__locales/fr.json'),
    hr: () => import(/* webpackChunkName: "locale.hr" */ 'panel/__locales/hr.json'),
    hu: () => import(/* webpackChunkName: "locale.hu" */ 'panel/__locales/hu.json'),
    id: () => import(/* webpackChunkName: "locale.id" */ 'panel/__locales/id.json'),
    it: () => import(/* webpackChunkName: "locale.it" */ 'panel/__locales/it.json'),
    ja: () => import(/* webpackChunkName: "locale.ja" */ 'panel/__locales/ja.json'),
    ko: () => import(/* webpackChunkName: "locale.ko" */ 'panel/__locales/ko.json'),
    nl: () => import(/* webpackChunkName: "locale.nl" */ 'panel/__locales/nl.json'),
    no: () => import(/* webpackChunkName: "locale.no" */ 'panel/__locales/no.json'),
    pl: () => import(/* webpackChunkName: "locale.pl" */ 'panel/__locales/pl.json'),
    'pt-br': () => import(/* webpackChunkName: "locale.pt-br" */ 'panel/__locales/pt-br.json'),
    'pt-pt': () => import(/* webpackChunkName: "locale.pt-pt" */ 'panel/__locales/pt-pt.json'),
    ro: () => import(/* webpackChunkName: "locale.ro" */ 'panel/__locales/ro.json'),
    ru: () => import(/* webpackChunkName: "locale.ru" */ 'panel/__locales/ru.json'),
    'si-lk': () => import(/* webpackChunkName: "locale.si-lk" */ 'panel/__locales/si-lk.json'),
    sk: () => import(/* webpackChunkName: "locale.sk" */ 'panel/__locales/sk.json'),
    sl: () => import(/* webpackChunkName: "locale.sl" */ 'panel/__locales/sl.json'),
    'sr-cs': () => import(/* webpackChunkName: "locale.sr-cs" */ 'panel/__locales/sr-cs.json'),
    sv: () => import(/* webpackChunkName: "locale.sv" */ 'panel/__locales/sv.json'),
    th: () => import(/* webpackChunkName: "locale.th" */ 'panel/__locales/th.json'),
    tr: () => import(/* webpackChunkName: "locale.tr" */ 'panel/__locales/tr.json'),
    uk: () => import(/* webpackChunkName: "locale.uk" */ 'panel/__locales/uk.json'),
    vi: () => import(/* webpackChunkName: "locale.vi" */ 'panel/__locales/vi.json'),
    'zh-cn': () => import(/* webpackChunkName: "locale.zh-cn" */ 'panel/__locales/zh-cn.json'),
    'zh-hk': () => import(/* webpackChunkName: "locale.zh-hk" */ 'panel/__locales/zh-hk.json'),
    'zh-tw': () => import(/* webpackChunkName: "locale.zh-tw" */ 'panel/__locales/zh-tw.json'),
};

export const LOCALE_CODES = new Set([
    'ar',
    'be',
    'bg',
    'cs',
    'da',
    'de',
    'en',
    'es',
    'fa',
    'fi',
    'fr',
    'hr',
    'hu',
    'id',
    'it',
    'ja',
    'ko',
    'nl',
    'no',
    'pl',
    'pt-br',
    'pt-pt',
    'ro',
    'ru',
    'si-lk',
    'sk',
    'sl',
    'sr-cs',
    'sv',
    'th',
    'tr',
    'uk',
    'vi',
    'zh-cn',
    'zh-hk',
    'zh-tw',
]);

export const LOCALES: Record<string, LocaleMessage> = {
    en: en,
};
