package aghhttp

import (
	"io/fs"
	"net/http"
	"path"
	"strings"

	"github.com/AdguardTeam/golibs/httphdr"
)

// Cache-Control header values.
const (
	cacheControlImmutable = "public, max-age=31536000, immutable"
	cacheControlNoCache   = "no-cache"
)

// frontendHashLength is the length of hashes generated by Webpack for the
// frontend filenames.
const frontendHashLength = 20

// cacheControlResponseWriter ensures that the selected cache policy survives
// calls to [http.ServeContent], which may remove caching headers on errors.
type cacheControlResponseWriter struct {
	http.ResponseWriter

	cacheControl string
}

// WriteHeader implements the [http.ResponseWriter] interface for
// *cacheControlResponseWriter.
func (w *cacheControlResponseWriter) WriteHeader(code int) {
	cacheControl := w.cacheControl
	if (code < http.StatusOK || code >= http.StatusMultipleChoices) &&
		code != http.StatusNotModified {
		cacheControl = cacheControlNoCache
	}

	w.Header().Set(httphdr.CacheControl, cacheControl)
	w.ResponseWriter.WriteHeader(code)
}

// Unwrap returns the underlying response writer.
func (w *cacheControlResponseWriter) Unwrap() (rw http.ResponseWriter) {
	return w.ResponseWriter
}

// NewStaticFileServer returns a handler that serves files from fsys with safe
// browser caching.  Existing regular files with fingerprinted frontend names
// are cached as immutable, while all other responses must be revalidated.
func NewStaticFileServer(fsys fs.FS) (h http.Handler) {
	fileServer := http.FileServer(http.FS(fsys))

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		cacheControl := staticCacheControl(fsys, r.URL.Path)
		wrapped := &cacheControlResponseWriter{
			ResponseWriter: w,
			cacheControl:   cacheControl,
		}
		wrapped.Header().Set(httphdr.CacheControl, cacheControl)

		fileServer.ServeHTTP(wrapped, r)
	})
}

// staticCacheControl returns the cache-control value for urlPath in fsys.
func staticCacheControl(fsys fs.FS, urlPath string) (value string) {
	if path.Clean(urlPath) != urlPath || !strings.HasPrefix(urlPath, "/") {
		return cacheControlNoCache
	}

	name := strings.TrimPrefix(urlPath, "/")
	if !fs.ValidPath(name) || !isFingerprintedFrontendAsset(name) {
		return cacheControlNoCache
	}

	info, err := fs.Stat(fsys, name)
	if err != nil || !info.Mode().IsRegular() {
		return cacheControlNoCache
	}

	return cacheControlImmutable
}

// isFingerprintedFrontendAsset reports whether name follows a filename pattern
// generated by the frontend's production Webpack configuration.
func isFingerprintedFrontendAsset(name string) (ok bool) {
	ext := path.Ext(name)
	switch strings.ToLower(ext) {
	case ".css", ".gif", ".ico", ".jpeg", ".jpg", ".js", ".png", ".svg", ".webp", ".woff", ".woff2":
		// Go on.
	default:
		return false
	}

	base := strings.TrimSuffix(path.Base(name), ext)
	dotIdx := strings.LastIndexByte(base, '.')
	if dotIdx < 0 {
		return false
	}

	hash := base[dotIdx+1:]
	if len(hash) != frontendHashLength {
		return false
	}

	for _, b := range []byte(hash) {
		if (b < '0' || b > '9') && (b < 'a' || b > 'f') {
			return false
		}
	}

	return true
}
