---
# This part of the release build is separate from the one described in
# release.yaml, because the Snapcraft infrastructure is brittle, and timeouts
# during logins and uploads often lead to release blocking.
'version': 2
'plan':
    'project-key': 'AGH'
    'key': 'AGHSNAP'
    'name': 'AdGuard Home - Build and publish Snapcraft release'
# Make sure to sync any changes with the branch overrides below.
'variables':
    # This variable is used to override Docker caching, for example to rerun a
    # flaky test suite.
    'cacheBuster': '0'
    'channel': 'edge'
    'dockerSnap': 'adguard/snap-builder:2.1'
    'snapcraftChannel': 'edge'

'stages':
  - 'Build packages':
        'manual': false
        'final': false
        'jobs':
          - 'Build packages'

  - 'Publish to Snapstore':
        'manual': false
        'final': false
        'jobs':
          - 'Publish to Snapstore'

'Build packages':
    'artifacts':
      - 'name': 'i386_snap'
        'pattern': 'AdGuardHome_i386.snap'
        'shared': true
        'required': true
      - 'name': 'amd64_snap'
        'pattern': 'AdGuardHome_amd64.snap'
        'shared': true
        'required': true
      - 'name': 'armhf_snap'
        'pattern': 'AdGuardHome_armhf.snap'
        'shared': true
        'required': true
      - 'name': 'arm64_snap'
        'pattern': 'AdGuardHome_arm64.snap'
        'shared': true
        'required': true
    'key': 'BP'
    'other':
        'clean-working-dir': true
    'tasks':
      - 'checkout':
            'force-clean-build': true
      - 'script':
            'interpreter': 'SHELL'
            'scripts':
            - |
              #!/bin/sh

              set -e -f -u -x

              docker info

              docker build \
                  --build-arg "BASE_IMAGE=${bamboo_dockerSnap}" \
                  --build-arg "CACHE_BUSTER=${bamboo_cacheBuster}" \
                  --build-arg "CHANNEL=${bamboo_channel}" \
                  --build-arg "VERSION=${bamboo_buildNumber}" \
                  --output '.' \
                  --progress 'plain' \
                  --target 'builder-exporter' \
                  -f ./docker/snapcraft.Dockerfile \
                  .

'Publish to Snapstore':
    'artifact-subscriptions':
      - 'artifact': 'i386_snap'
      - 'artifact': 'amd64_snap'
      - 'artifact': 'armhf_snap'
      - 'artifact': 'arm64_snap'
    'key': 'PTS'
    'other':
        'clean-working-dir': true
    'final-tasks':
      - 'clean'
    'tasks':
      - 'checkout':
            'force-clean-build': true
      - 'script':
            'interpreter': 'SHELL'
            'scripts':
              - |
                #!/bin/sh

                set -e -f -u -x

                docker info

                docker build \
                    --build-arg "BASE_IMAGE=${bamboo_dockerSnap}" \
                    --build-arg "CACHE_BUSTER=${bamboo_cacheBuster}" \
                    --build-arg "SNAPCRAFT_CHANNEL=${bamboo_snapcraftChannel}" \
                    --build-arg "SNAPCRAFT_STORE_CREDENTIALS=${bamboo_snapcraftMacaroonPassword}" \
                    --build-arg "VERSION=${bamboo_buildNumber}" \
                    --output '.' \
                    --progress 'plain' \
                    --target 'publisher' \
                    -f ./docker/snapcraft.Dockerfile \
                    .

'triggers':
    # Don't use minute values that end with a zero or a five as these are often
    # used in CI and so resources during these minutes can be quite busy.
    #
    # NOTE: The time is chosen to be exactly one hour after the main release
    # build as defined as in release.yaml.
  - 'cron': '0 42 14 ? * MON-FRI *'
'branches':
    'create': 'manually'
    'delete':
        'after-deleted-days': 1
        'after-inactive-days': 30
    'integration':
        'push-on-success': false
        'merge-from': 'AdGuard Home - Build and publish Snapcraft release'
    'link-to-jira': true

'notifications':
  - 'events':
      - 'plan-completed'
    'recipients':
      - 'webhook':
            'name': 'Build webhook'
            'url': 'http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-qa-dns-builds'

'labels': []
'other':
    'concurrent-build-plugin': 'system-default'

'branch-overrides':
    # beta-vX.Y branches are the branches into which the commits that are needed
    # to release a new patch version are initially cherry-picked.
  - '^beta-v[0-9]+\.[0-9]+':
        # Build betas on release branches manually.
        'triggers': []
        # Set the default release channel on the release branch to beta, as we may
        # need to build a few of these.
        'variables':
            'channel': 'beta'
            'dockerSnap': 'adguard/snap-builder:2.1'
            'snapcraftChannel': 'beta'
    # release-vX.Y.Z branches are the branches from which the actual final
    # release is built.
  - '^release-v[0-9]+\.[0-9]+\.[0-9]+':
        # Disable integration branches for release branches.
        'branch-config':
            'integration':
                'push-on-success': false
                'merge-from': 'beta-v0.107'
        # Build final releases on release branches manually.
        'triggers': []
        # Set the default release channel on the final branch to release, as these
        # are the ones that actually get released.
        'variables':
            'channel': 'release'
            'dockerSnap': 'adguard/snap-builder:2.1'
            'snapcraftChannel': 'candidate'
