'name': 'lint'
# Permissions are disabled for all the jobs by default, and then overridden for
# specific jobs if needed.  This is a recommended practice for security reasons,
# and also allows to avoid mistakes with permissions when creating new jobs.
#
# See https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions.
'permissions': {}
'env':
  'GO_VERSION': '1.26.2'
'on':
  'push':
    'tags':
      - 'v*'
    'branches':
      - '*'
  'pull_request':
'jobs':
  'go-lint':
    'runs-on': 'ubuntu-latest'
    'permissions':
      'contents': 'read'
    'steps':
      - 'uses': 'actions/checkout@v2'
        'with':
          # Set to false to avoid  GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': 'Set up Go'
        'uses': 'actions/setup-go@v3'
        'with':
          'go-version': '${{ env.GO_VERSION }}'
      - 'name': 'run-lint'
        'run': >
          make go-deps go-lint

  'eslint':
    'runs-on': 'ubuntu-latest'
    'permissions':
      'contents': 'read'
    'steps':
      - 'uses': 'actions/checkout@v2'
        'with':
          # Set to false to avoid  GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': 'Install modules'
        'run': 'npm --prefix="./client" ci'
      - 'name': 'Run ESLint'
        'run': 'npm --prefix="./client" run lint'
  'notify':
    'needs':
      - 'go-lint'
      - 'eslint'
    # Secrets are not passed to workflows that are triggered by a pull request
    # from a fork.
    #
    # Use always() to signal to the runner that this job must run even if the
    # previous ones failed.
    'if': |
      ${{
        always() &&
        github.repository_owner == 'AdguardTeam' &&
        (
          github.event_name == 'push' ||
          github.event.pull_request.head.repo.full_name == github.repository
        )
      }}
    'runs-on': 'ubuntu-latest'
    'permissions':
      # Required by workflow-conclusion-action to check workflow status.
      'actions': 'read'
      'contents': 'read'
    'steps':
      - 'name': 'Conclusion'
        'uses': 'technote-space/workflow-conclusion-action@v1'
      - 'name': 'Send Slack notif'
        'uses': '8398a7/action-slack@v3'
        'with':
          'status': '${{ env.WORKFLOW_CONCLUSION }}'
          'fields': 'repo, message, commit, author, workflow'
        'env':
          'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}'
          'SLACK_WEBHOOK_URL': '${{ secrets.SLACK_WEBHOOK_URL }}'
